name: Bug Report
description: File a bug report.
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        This repository's issue tracker is only for the RPM packaging. If you believe you've found a bug in the upstream GPU Screen Recorder application itself or have a feature request, please see [here](https://git.dec05eba.com/?p=about).

        Issues that do not follow the template may be automatically closed. Issues that look like upstream bugs may be closed automatically by evil robots.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues.
        required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what happened.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: What did you expect?
      description: What did you expect to happen?
      placeholder: I expected ...
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of GSR are you running?

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false